name: Build Manuals

on:
  workflow_dispatch:
  repository_dispatch:
    types: [release-published]

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  BuildManuals:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Install Jekyll"
        run: |
          sudo apt-get install ruby-full build-essential zlib1g-dev
          export GEM_HOME="$HOME/gems"
          export PATH="$HOME/gems/bin:$PATH"
          gem install jekyll bundler
      - name: "Install Doxygen"
        run: |
          sudo apt-get install doxygen
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Build Manuals"
        run: |
          export GEM_HOME="$HOME/gems"
          export PATH="$HOME/gems/bin:$PATH"
          python master.py
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      - name: "Upload Manuals"
        uses: actions/upload-artifact@v4
        with:
          name: FEBioManuals
          path: |
            jekyll/**/_site
